package com.kabadi.calc

/** UI text in English (0), Hindi (1), Gujarati (2). */
object L {
    var lang = 0

    private val T: Map<String, Array<String>> = mapOf(
        "app" to arrayOf("Kabadi Market Hisab", "कबाड़ी मार्केट हिसाब", "કબાડી માર્કેટ હિસાબ"),
        "new" to arrayOf("+ New Hisab", "+ नया हिसाब", "+ નવો હિસાબ"),
        "saved" to arrayOf("Saved hisab", "पुराने हिसाब", "જૂના હિસાબ"),
        "none" to arrayOf("No hisab yet. Tap + New Hisab.", "अभी कोई हिसाब नहीं। + नया हिसाब दबाएँ।", "હજી કોઈ હિસાબ નથી. + નવો હિસાબ દબાવો."),
        "settings" to arrayOf("Settings", "सेटिंग", "સેટિંગ"),
        "calc" to arrayOf("Calculator", "कैलकुलेटर", "કેલ્ક્યુલેટર"),
        "owner" to arrayOf("Owner / shop name", "मालिक / दुकान का नाम", "માલિક / દુકાનનું નામ"),
        "mobile" to arrayOf("Mobile number", "मोबाइल नंबर", "મોબાઇલ નંબર"),
        "address" to arrayOf("Address (optional)", "पता (ज़रूरी नहीं)", "સરનામું (જરૂરી નથી)"),
        "party" to arrayOf("Party name", "पार्टी का नाम", "પાર્ટીનું નામ"),
        "vehicle" to arrayOf("Vehicle no. / model", "गाड़ी नंबर / मॉडल", "ગાડી નંબર / મોડલ"),
        "note" to arrayOf("Note", "नोट", "નોંધ"),
        "date" to arrayOf("Date & time", "तारीख और समय", "તારીખ અને સમય"),
        "price" to arrayOf("1. Vehicle price", "1. गाड़ी की कीमत", "1. ગાડીની કિંમત"),
        "kharch" to arrayOf("2. Expenses (tap to add)", "2. खर्च (दबाकर जोड़ें)", "2. ખર્ચ (દબાવીને ઉમેરો)"),
        "maal" to arrayOf("3. Parts / maal (tap to add)", "3. माल (दबाकर जोड़ें)", "3. માલ (દબાવીને ઉમેરો)"),
        "other" to arrayOf("+ Other", "+ दूसरा", "+ બીજું"),
        "kg" to arrayOf("Kg", "किलो", "કિલો"),
        "rate" to arrayOf("Rate ₹/kg", "भाव ₹/किलो", "ભાવ ₹/કિલો"),
        "fix" to arrayOf("Fix", "फिक्स", "ફિક્સ"),
        "ltr" to arrayOf("Litre", "लीटर", "લીટર"),
        "rate_l" to arrayOf("Rate ₹/litre", "भाव ₹/लीटर", "ભાવ ₹/લીટર"),
        "ltrrate" to arrayOf("Litre × Rate", "लीटर × भाव", "લીટર × ભાવ"),
        "sum_ltr" to arrayOf("Total litre", "कुल लीटर", "કુલ લીટર"),
        "qty" to arrayOf("Qty", "मात्रा", "જથ્થો"),
        "kgrate" to arrayOf("Kg × Rate", "किलो × भाव", "કિલો × ભાવ"),
        "amount" to arrayOf("Amount ₹", "रकम ₹", "રકમ ₹"),
        "total" to arrayOf("Total", "कुल", "કુલ"),
        "sum_price" to arrayOf("Vehicle price", "गाड़ी की कीमत", "ગાડીની કિંમત"),
        "sum_kharch" to arrayOf("Total expenses", "कुल खर्च", "કુલ ખર્ચ"),
        "sum_lagat" to arrayOf("Total cost (price + expenses)", "कुल लागत (कीमत + खर्च)", "કુલ લાગત (કિંમત + ખર્ચ)"),
        "sum_maal" to arrayOf("Parts total", "माल का कुल", "માલનો કુલ"),
        "sum_kg" to arrayOf("Total weight", "कुल वज़न", "કુલ વજન"),
        "profit" to arrayOf("PROFIT", "मुनाफा", "નફો"),
        "loss" to arrayOf("LOSS", "नुकसान", "નુકસાન"),
        "save" to arrayOf("Save", "सेव", "સેવ"),
        "jpg" to arrayOf("JPG", "JPG", "JPG"),
        "pdf" to arrayOf("PDF", "PDF", "PDF"),
        "share" to arrayOf("WhatsApp", "WhatsApp", "WhatsApp"),
        "delete" to arrayOf("Delete", "हटाएँ", "કાઢી નાખો"),
        "back" to arrayOf("Back", "वापस", "પાછા"),
        "saved_ok" to arrayOf("Saved", "सेव हो गया", "સેવ થઈ ગયું"),
        "del_q" to arrayOf("Delete this hisab?", "यह हिसाब हटाएँ?", "આ હિસાબ કાઢી નાખવો?"),
        "yes" to arrayOf("Yes", "हाँ", "હા"),
        "no" to arrayOf("No", "नहीं", "ના"),
        "lang" to arrayOf("Language", "भाषा", "ભાષા"),
        "name_q" to arrayOf("Name", "नाम", "નામ"),
        "hisab" to arrayOf("HISAB", "हिसाब", "હિસાબ"),
        "item" to arrayOf("Item", "आइटम", "વસ્તુ"),
        "img_ok" to arrayOf("Saved in Gallery (Pictures/KabadiCalc)", "गैलरी में सेव (Pictures/KabadiCalc)", "ગેલેરીમાં સેવ (Pictures/KabadiCalc)"),
        "pdf_ok" to arrayOf("Saved in Downloads/KabadiCalc", "Downloads/KabadiCalc में सेव", "Downloads/KabadiCalc માં સેવ"),
        "perm" to arrayOf("Allow storage permission and tap again", "स्टोरेज की अनुमति दें और फिर दबाएँ", "સ્ટોરેજની મંજૂરી આપો અને ફરી દબાવો"),
        "update" to arrayOf("Check for update", "अपडेट देखें", "અપડેટ તપાસો"),
        "lists" to arrayOf("My lists (add / remove buttons)", "मेरी लिस्ट (बटन जोड़ें / हटाएँ)", "મારી યાદી (બટન ઉમેરો / કાઢો)"),
        "parts_list" to arrayOf("Parts buttons", "माल के बटन", "માલના બટન"),
        "exp_list" to arrayOf("Expense buttons", "खर्च के बटन", "ખર્ચના બટન"),
        "add" to arrayOf("Add", "जोड़ें", "ઉમેરો"),
        "reset" to arrayOf("Default", "डिफ़ॉल्ट", "ડિફોલ્ટ"),
        "tip" to arrayOf(
            "Tip: in any box you can type 400+380 or 2*55.",
            "टिप: किसी भी खाने में 400+380 या 2*55 लिख सकते हैं।",
            "ટીપ: કોઈ પણ ખાનામાં 400+380 કે 2*55 લખી શકો છો."
        ),
        "search" to arrayOf("Search party / vehicle", "पार्टी / गाड़ी खोजें", "પાર્ટી / ગાડી શોધો"),
        "all_total" to arrayOf("All hisab profit", "सब हिसाब का मुनाफा", "બધા હિસાબનો નફો"),
        "copy" to arrayOf("Copy", "कॉपी", "કૉપિ"),
        "new_gaadi" to arrayOf("+ Vehicle hisab", "+ गाड़ी हिसाब", "+ ગાડી હિસાબ"),
        "new_haraji" to arrayOf("+ Auction / Company hisab", "+ हराजी / कंपनी हिसाब", "+ હરાજી / કંપની હિસાબ"),
        "haraji" to arrayOf("AUCTION", "हराजी", "હરાજી"),
        "buy_price" to arrayOf("1. Auction buying price", "1. हराजी में खरीदी कीमत", "1. હરાજીમાં ખરીદ કિંમત"),
        "sale" to arrayOf("4. Sold in auction (amount)", "4. हराजी में बेचा (रकम)", "4. હરાજીમાં વેચ્યું (રકમ)"),
        "sale_s" to arrayOf("Auction sale", "हराजी बिक्री", "હરાજી વેચાણ"),
        "comm" to arrayOf("5. Market commission", "5. मार्केट कमीशन", "5. માર્કેટ કમિશન"),
        "comm_s" to arrayOf("Market commission", "मार्केट कमीशन", "માર્કેટ કમિશન"),
        "pct" to arrayOf("%", "%", "%"),
        "fixamt" to arrayOf("Fixed ₹", "फिक्स ₹", "ફિક્સ ₹"),
        "bikri" to arrayOf("Total sale", "कुल बिक्री", "કુલ વેચાણ"),
        "company" to arrayOf("6. Company (partners)", "6. कंपनी (भागीदार)", "6. કંપની (ભાગીદાર)"),
        "partner" to arrayOf("Partner name", "भागीदार का नाम", "ભાગીદારનું નામ"),
        "pshare" to arrayOf("Paise (%)", "पैसे (%)", "પૈસા (%)"),
        "add_partner" to arrayOf("+ Partner", "+ भागीदार", "+ ભાગીદાર"),
        "owner_share" to arrayOf("Remaining (owner)", "बाकी (मालिक)", "બાકી (માલિક)"),
        "over100" to arrayOf("Shares are more than 100 paise!", "हिस्से 100 पैसे से ज़्यादा हैं!", "ભાગ 100 પૈસાથી વધારે છે!"),
        "invest" to arrayOf("Money in", "लगाया", "રોક્યા"),
        "gets" to arrayOf("Gets back", "वापस मिलेगा", "પાછા મળશે"),
        "dup" to arrayOf("Already in this hisab", "यह पहले से हिसाब में है", "આ પહેલેથી હિસાબમાં છે"),
        "dup_save" to arrayOf("Same item twice", "एक ही आइटम दो बार", "એક જ વસ્તુ બે વાર"),
        "learned" to arrayOf("New button added", "नया बटन जुड़ा", "નવું બટન ઉમેરાયું"),
        "del_line" to arrayOf("Remove this line?", "यह लाइन हटाएँ?", "આ લાઇન કાઢવી?"),
        "undo" to arrayOf("Undo", "वापस लाएँ", "પાછું લાવો"),
        "removed" to arrayOf("Removed", "हटाया", "કાઢ્યું"),
        "restore" to arrayOf("Reset (bring back deleted)", "रीसेट (हटाए हुए वापस)", "રીસેટ (કાઢેલા પાછા)"),
        "role_q" to arrayOf("Whose hisab is this?", "यह हिसाब किसका है?", "આ હિસાબ કોનો છે?"),
        "buyer" to arrayOf("Buyer (taking maal)", "बायर (माल लेने वाला)", "બાયર (માલ લેનાર)"),
        "seller" to arrayOf("Seller (selling maal)", "सेलर (माल बेचने वाला)", "સેલર (માલ વેચનાર)"),
        "buyer_s" to arrayOf("Buyer", "बायर", "બાયર"),
        "seller_s" to arrayOf("Seller", "सेलर", "સેલર"),
        "vinfo" to arrayOf("Vehicle details", "गाड़ी की जानकारी", "ગાડીની વિગત"),
        "brand" to arrayOf("Brand", "ब्रांड", "બ્રાન્ડ"),
        "variant" to arrayOf("Variant / model (1612, 2515…)", "वेरिएंट / मॉडल (1612, 2515…)", "વેરિયન્ટ / મોડલ (1612, 2515…)"),
        "tyres" to arrayOf("Tyres", "टायर", "ટાયર"),
        "year" to arrayOf("Year", "साल", "વર્ષ"),
        "place" to arrayOf("Bought from (village / city)", "कहाँ से ली (गाँव / शहर)", "ક્યાંથી લીધી (ગામ / શહેર)"),
        "rokad" to arrayOf("Cash", "रोकड़", "રોકડ"),
        "udhaar" to arrayOf("Credit", "उधार", "ઉધાર"),
        "baaki" to arrayOf("Unpaid", "बाकी", "બાકી"),
        "chukaya" to arrayOf("Paid", "चुकाया", "ચૂકવ્યું"),
        "sell" to arrayOf("3. Sell items (tap to add)", "3. बेचान / Sell item (दबाकर जोड़ें)", "3. વેચાણ / Sell item (દબાવીને ઉમેરો)"),
        "sell_s" to arrayOf("Sold items", "बेचान", "વેચાણ"),
        "cname" to arrayOf("Taken by (name)", "लेने वाले का नाम", "લેનારનું નામ"),
        "cmobile" to arrayOf("Mobile", "मोबाइल", "મોબાઇલ"),
        "days" to arrayOf("Credit days", "उधार की मुद्दत (दिन)", "ઉધારની મુદત (દિવસ)"),
        "gname" to arrayOf("Guarantor (jamindar)", "जमींदार का नाम", "જામીનદારનું નામ"),
        "gmobile" to arrayOf("Guarantor mobile", "जमींदार मोबाइल", "જામીનદાર મોબાઇલ"),
        "shop" to arrayOf("Shop number", "दुकान नंबर", "દુકાન નંબર"),
        "dena_baaki" to arrayOf("Expenses still to pay", "खर्च देना बाकी", "ખર્ચ ચૂકવવાનો બાકી"),
        "lena_baaki" to arrayOf("Sold on credit (to collect)", "उधार बेचा (लेना बाकी)", "ઉધાર વેચ્યું (લેવાનું બાકી)"),
        "rokad_bikri" to arrayOf("Sold for cash", "रोकड़ बिक्री", "રોકડ વેચાણ"),
        "due" to arrayOf("Due", "मुद्दत", "મુદત"),
        "khata" to arrayOf("Credit book (lena / dena)", "उधार खाता (लेना / देना)", "ઉધાર ખાતું (લેવાનું / આપવાનું)"),
        "khata_btn" to arrayOf("📒 Credit book", "📒 उधार खाता", "📒 ઉધાર ખાતું"),
        "n_title" to arrayOf("Credit muddat today / over", "उधार की मुद्दत आज / पूरी", "ઉધારની મુદત આજે / પૂરી"),
        "lena" to arrayOf("To collect", "लेना है", "લેવાનું"),
        "dena" to arrayOf("To pay", "देना है", "આપવાનું"),
        "overdue" to arrayOf("Muddat over", "मुद्दत पूरी", "મુદત પૂરી"),
        "today" to arrayOf("Today", "आज", "આજે"),
        "no_due" to arrayOf("No open credit", "कोई उधार बाकी नहीं", "કોઈ ઉધાર બાકી નથી"),
        "kist" to arrayOf("+ Installment", "+ किस्त", "+ હપ્તો"),
        "kist_amt" to arrayOf("Installment amount ₹", "किस्त की रकम ₹", "હપ્તાની રકમ ₹"),
        "got" to arrayOf("Received", "मिला", "મળ્યા"),
        "gave" to arrayOf("Paid", "दिया", "આપ્યા"),
        "left" to arrayOf("Left", "बाकी", "બાકી"),
        "remind" to arrayOf("💬 Reminder", "💬 याद दिलाएँ", "💬 યાદ અપાવો"),
        "split" to arrayOf("Mudiwala / Khedut (profit share)", "मुडीवाला / खेडूत (मुनाफे का भाग)", "મૂડીવાળો / ખેડૂત (નફાનો ભાગ)"),
        "mudi" to arrayOf("Mudiwala (money)", "मुडीवाला", "મૂડીવાળો"),
        "khed" to arrayOf("Khedut (work)", "खेडूत", "ખેડૂત"),
        "pct_hint" to arrayOf("% share", "% भाग", "% ભાગ"),
        "not100" to arrayOf("Total is not 100%", "कुल 100% नहीं है", "કુલ 100% નથી"),
        "check_bad" to arrayOf("Total mismatch – please check the numbers", "टोटल मेल नहीं खा रहा – आंकड़े जाँचें", "ટોટલ મેળ નથી ખાતો – આંકડા તપાસો"),
        "check_ok" to arrayOf("✓ Totals checked twice", "✓ टोटल दो बार जाँचा", "✓ ટોટલ બે વાર તપાસ્યું"),
        "open" to arrayOf("Open", "खोलें", "ખોલો"),
        "role_s" to arrayOf("Type", "प्रकार", "પ્રકાર"),
        "mudi_h" to arrayOf("Mudi malik", "मुडी मालिक", "મૂડી માલિક"),
        "khed_h" to arrayOf("Khedut", "खेडूत", "ખેડૂત"),
        "report_btn" to arrayOf("📊 Report", "📊 रिपोर्ट", "📊 રિપોર્ટ"),
        "report" to arrayOf("Monthly report", "महीने की रिपोर्ट", "મહિનાનો રિપોર્ટ"),
        "filter_name" to arrayOf("Mudi malik / Khedut name (optional)", "मुडी मालिक / खेडूत का नाम (ज़रूरी नहीं)", "મૂડી માલિક / ખેડૂતનું નામ (જરૂરી નથી)"),
        "vehicles" to arrayOf("Hisab", "हिसाब", "હિસાબ"),
        "kharidi" to arrayOf("Bought (vehicle)", "खरीदी (गाड़ी)", "ખરીદી (ગાડી)"),
        "all_months" to arrayOf("All months", "सब महीने", "બધા મહિના"),
        "backup" to arrayOf("Backup (phone kho jaye to bhi hisab safe)", "बैकअप (फ़ोन खो जाए तो भी हिसाब सुरक्षित)", "બેકઅપ (ફોન ખોવાય તો પણ હિસાબ સલામત)"),
        "backup_make" to arrayOf("💾 Make backup & send", "💾 बैकअप बनाएँ और भेजें", "💾 બેકઅપ બનાવો અને મોકલો"),
        "backup_load" to arrayOf("📂 Restore from backup file", "📂 बैकअप फ़ाइल से वापस लाएँ", "📂 બેકઅપ ફાઇલથી પાછું લાવો"),
        "backup_ok" to arrayOf("Backup saved in Downloads/KabadiCalc", "बैकअप Downloads/KabadiCalc में सेव", "બેકઅપ Downloads/KabadiCalc માં સેવ"),
        "restored" to arrayOf("Hisab restored", "हिसाब वापस आए", "હિસાબ પાછા આવ્યા"),
        "bad_file" to arrayOf("This is not a Kabadi Market Hisab backup", "यह कबाड़ी मार्केट हिसाब का बैकअप नहीं है", "આ કબાડી માર્કેટ હિસાબનો બેકઅપ નથી"),
        "last_backup" to arrayOf("Last backup", "आखिरी बैकअप", "છેલ્લો બેકઅપ"),
        "send_list" to arrayOf("💬 Send list on WhatsApp", "💬 लिस्ट WhatsApp पर भेजें", "💬 યાદી WhatsApp પર મોકલો"),
        "more" to arrayOf("Mobile / note", "मोबाइल / नोट", "મોબાઇલ / નોંધ"),
        "f_mudi" to arrayOf("Mudi malik", "मुडी मालिक", "મૂડી માલિક"),
        "f_year" to arrayOf("Year", "साल", "વર્ષ"),
        "f_month" to arrayOf("Month", "महीना", "મહિનો"),
        "f_brand" to arrayOf("Vehicle", "गाड़ी", "ગાડી"),
        "f_tyre" to arrayOf("Tyres", "चक्का", "ચક્કા"),
        "f_type" to arrayOf("Type", "प्रकार", "પ્રકાર"),
        "f_all" to arrayOf("All", "सब", "બધા"),
        "f_clear" to arrayOf("✕ Clear filter", "✕ फ़िल्टर हटाएँ", "✕ ફિલ્ટર હટાવો"),
        "f_search" to arrayOf("Search name / vehicle no. / place", "नाम / गाड़ी नं. / जगह खोजें", "નામ / ગાડી નં. / જગ્યા શોધો"),
        "f_list" to arrayOf("Vehicles", "गाड़ियाँ", "ગાડીઓ"),
        "tyre_s" to arrayOf("tyre", "चक्का", "ચક્કા"),
        "gaadi_s" to arrayOf("Vehicle hisab", "गाड़ी हिसाब", "ગાડી હિસાબ"),
        "acc_new" to arrayOf("Create your account", "अपना खाता बनाएँ", "તમારું ખાતું બનાવો"),
        "acc_name" to arrayOf("Your name / shop name", "आपका नाम / दुकान का नाम", "તમારું નામ / દુકાનનું નામ"),
        "acc_mobile" to arrayOf("Mobile number (10 digit)", "मोबाइल नंबर (10 अंक)", "મોબાઇલ નંબર (10 આંકડા)"),
        "acc_pin" to arrayOf("Set 4-digit PIN", "4 अंक का PIN बनाएँ", "4 આંકડાનો PIN બનાવો"),
        "acc_pin2" to arrayOf("PIN again", "PIN फिर से", "PIN ફરીથી"),
        "acc_open" to arrayOf("Open", "खोलें", "ખોલો"),
        "acc_enter" to arrayOf("Enter PIN", "PIN डालें", "PIN નાખો"),
        "acc_wrong" to arrayOf("Wrong PIN", "गलत PIN", "ખોટો PIN"),
        "acc_bad_mobile" to arrayOf("Write full 10 digit mobile", "पूरा 10 अंक का मोबाइल लिखें", "પૂરો 10 આંકડાનો મોબાઇલ લખો"),
        "acc_bad_pin" to arrayOf("PIN must be 4 digits and both same", "PIN 4 अंक का हो और दोनों एक जैसे", "PIN 4 આંકડાનો અને બંને સરખા હોવા જોઈએ"),
        "acc_forgot" to arrayOf("Forgot PIN?", "PIN भूल गए?", "PIN ભૂલી ગયા?"),
        "acc_forgot_q" to arrayOf("Write your registered mobile number to set a new PIN", "नया PIN बनाने के लिए अपना रजिस्टर मोबाइल नंबर लिखें", "નવો PIN બનાવવા તમારો રજીસ્ટર મોબાઇલ નંબર લખો"),
        "acc_sec" to arrayOf("Account & PIN lock", "खाता और PIN लॉक", "ખાતું અને PIN લોક"),
        "acc_lock_on" to arrayOf("PIN lock: ON (tap to turn off)", "PIN लॉक: चालू (बंद करने के लिए दबाएँ)", "PIN લોક: ચાલુ (બંધ કરવા દબાવો)"),
        "acc_lock_off" to arrayOf("PIN lock: OFF (tap to turn on)", "PIN लॉक: बंद (चालू करने के लिए दबाएँ)", "PIN લોક: બંધ (ચાલુ કરવા દબાવો)"),
        "acc_change" to arrayOf("Change PIN", "PIN बदलें", "PIN બદલો"),
        "acc_note" to arrayOf("Your hisab stays only in this phone. Keep a backup.", "आपका हिसाब सिर्फ इसी फ़ोन में रहता है। बैकअप रखें।", "તમારો હિસાબ ફક્ત આ ફોનમાં રહે છે. બેકઅપ રાખો."),
        "otp_ask" to arrayOf("📲 Ask OTP (WhatsApp)", "📲 OTP माँगें (WhatsApp)", "📲 OTP માંગો (WhatsApp)"),
        "otp_why" to arrayOf("First time, admin sends you an OTP on WhatsApp.", "पहली बार, एडमिन आपको WhatsApp पर OTP भेजेंगे।", "પહેલી વાર, એડમિન તમને WhatsApp પર OTP મોકલશે."),
        "otp_title" to arrayOf("Enter the OTP from admin", "एडमिन का भेजा OTP डालें", "એડમિને મોકલેલો OTP નાખો"),
        "otp_code" to arrayOf("Phone code", "फ़ोन कोड", "ફોન કોડ"),
        "otp_help" to arrayOf("Send the request to admin on WhatsApp. When admin approves, you will get a 6-digit OTP.", "WhatsApp पर एडमिन को रिक्वेस्ट भेजें। एडमिन मंज़ूर करेंगे तो 6 अंक का OTP आएगा।", "WhatsApp પર એડમિનને રિક્વેસ્ટ મોકલો. એડમિન મંજૂર કરશે તો 6 આંકડાનો OTP આવશે."),
        "otp_send" to arrayOf("💬 Send request on WhatsApp", "💬 WhatsApp पर रिक्वेस्ट भेजें", "💬 WhatsApp પર રિક્વેસ્ટ મોકલો"),
        "otp_enter" to arrayOf("6-digit OTP", "6 अंक का OTP", "6 આંકડાનો OTP"),
        "otp_ok" to arrayOf("Approved ✓ Welcome", "मंज़ूर ✓ स्वागत है", "મંજૂર ✓ સ્વાગત છે"),
        "otp_bad" to arrayOf("Wrong OTP", "गलत OTP", "ખોટો OTP"),
        "otp_change" to arrayOf("✎ Change name / number", "✎ नाम / नंबर बदलें", "✎ નામ / નંબર બદલો"),
        "signin" to arrayOf("Sign in", "साइन इन", "સાઇન ઇન"),
        "signin_btn" to arrayOf("Sign in", "साइन इन", "સાઇન ઇન"),
        "other_acc" to arrayOf("Other number / new account", "दूसरा नंबर / नया खाता", "બીજો નંબર / નવું ખાતું"),
        "signout" to arrayOf("🚪 Sign out", "🚪 साइन आउट", "🚪 સાઇન આઉટ"),
        "signout_q" to arrayOf("Sign out? Your hisab stays safe in this phone. PIN is needed to sign in again.", "साइन आउट करें? हिसाब इसी फ़ोन में सुरक्षित रहेगा। फिर से खोलने के लिए PIN लगेगा।", "સાઇન આઉટ કરવું? હિસાબ આ ફોનમાં સલામત રહેશે. ફરી ખોલવા PIN જોઈશે."),
        "adm_btn" to arrayOf("Admin: make OTP", "एडमिन: OTP बनाएँ", "એડમિન: OTP બનાવો"),
        "adm_paste" to arrayOf("New request", "नई रिक्वेस्ट", "નવી રિક્વેસ્ટ"),
        "adm_paste_h" to arrayOf("Paste the WhatsApp request here", "WhatsApp रिक्वेस्ट यहाँ पेस्ट करें", "WhatsApp રિક્વેસ્ટ અહીં પેસ્ટ કરો"),
        "adm_fill" to arrayOf("Write mobile and phone code", "मोबाइल और फ़ोन कोड लिखें", "મોબાઇલ અને ફોન કોડ લખો"),
        "adm_ok" to arrayOf("✅ Approve – send OTP on WhatsApp", "✅ मंज़ूर – OTP WhatsApp पर भेजें", "✅ મંજૂર – OTP WhatsApp પર મોકલો"),
        "adm_ok_msg" to arrayOf("Enter this OTP in the app. It works only on your phone.", "यह OTP ऐप में डालें। यह सिर्फ आपके फ़ोन में चलेगा।", "આ OTP એપમાં નાખો. તે ફક્ત તમારા ફોનમાં ચાલશે."),
        "adm_no" to arrayOf("✕ Cancel", "✕ रद्द करें", "✕ રદ કરો"),
        "adm_no_msg" to arrayOf("Your request is rejected.", "आपकी रिक्वेस्ट रिजेक्ट हुई है।", "તમારી રિક્વેસ્ટ રિજેક્ટ થઈ છે."),
        "adm_no_title" to arrayOf("Admin WhatsApp number (requests come here)", "एडमिन WhatsApp नंबर (रिक्वेस्ट यहाँ आती है)", "એડમિન WhatsApp નંબર (રિક્વેસ્ટ અહીં આવે છે)"),
        "adm_no_set" to arrayOf("Not set yet – users choose the contact in WhatsApp", "अभी सेट नहीं – यूज़र WhatsApp में कॉन्टैक्ट चुनेंगे", "હજી સેટ નથી – યુઝર WhatsApp માં કોન્ટેક્ટ પસંદ કરશે"),
        "adm_log" to arrayOf("Approved / rejected", "मंज़ूर / रिजेक्ट", "મંજૂર / રિજેક્ટ"),
        "otp_wait" to arrayOf("Request sent. Waiting for admin…", "रिक्वेस्ट गई। एडमिन की मंज़ूरी का इंतज़ार…", "રિક્વેસ્ટ ગઈ. એડમિનની મંજૂરીની રાહ…"),
        "otp_sending" to arrayOf("Sending request…", "रिक्वेस्ट भेज रहे हैं…", "રિક્વેસ્ટ મોકલીએ છીએ…"),
        "otp_got" to arrayOf("Approved! OTP received – tap Open app", "मंज़ूर! OTP आ गया – ऐप खोलें दबाएँ", "મંજૂર! OTP આવી ગયો – એપ ખોલો દબાવો"),
        "otp_rejected" to arrayOf("Admin rejected the request", "एडमिन ने रिक्वेस्ट रिजेक्ट की", "એડમિને રિક્વેસ્ટ રિજેક્ટ કરી"),
        "otp_net" to arrayOf("No internet – will try again", "इंटरनेट नहीं – फिर से कोशिश होगी", "ઇન્ટરનેટ નથી – ફરી પ્રયત્ન થશે"),
        "otp_open" to arrayOf("🔓 Open app", "🔓 ऐप खोलें", "🔓 એપ ખોલો"),
        "otp_again" to arrayOf("Send request again", "रिक्वेस्ट फिर भेजें", "રિક્વેસ્ટ ફરી મોકલો"),
        "adm_req" to arrayOf("OTP requests", "OTP रिक्वेस्ट", "OTP રિક્વેસ્ટ"),
        "adm_req_none" to arrayOf("No new request", "कोई नई रिक्वेस्ट नहीं", "કોઈ નવી રિક્વેસ્ટ નથી"),
        "adm_req_new" to arrayOf("new OTP request – open", "नई OTP रिक्वेस्ट – देखें", "નવી OTP રિક્વેસ્ટ – જુઓ"),
        "adm_accept" to arrayOf("✅ Accept", "✅ मंज़ूर", "✅ મંજૂર"),
        "adm_manual" to arrayOf("Request came on WhatsApp? Paste it below:", "रिक्वेस्ट WhatsApp पर आई? नीचे पेस्ट करें:", "રિક્વેસ્ટ WhatsApp પર આવી? નીચે પેસ્ટ કરો:"),
        "adm_login" to arrayOf("Admin login", "एडमिन लॉगिन", "એડમિન લોગિન"),
        "adm_fill_first" to arrayOf("First write name, mobile and PIN, then Admin login", "पहले नाम, मोबाइल और PIN लिखें, फिर एडमिन लॉगिन", "પહેલા નામ, મોબાઇલ અને PIN લખો, પછી એડમિન લોગિન"),
        "crash_t" to arrayOf("The app closed last time", "पिछली बार ऐप बंद हो गई थी", "છેલ્લી વાર એપ બંધ થઈ ગઈ હતી"),
        "crash_h" to arrayOf("Send this error on WhatsApp so it can be fixed. Then tap Continue.", "यह एरर WhatsApp पर भेजें ताकि ठीक हो सके। फिर आगे बढ़ें दबाएँ।", "આ એરર WhatsApp પર મોકલો જેથી સુધારી શકાય. પછી આગળ વધો દબાવો."),
        "crash_send" to arrayOf("💬 Send error", "💬 एरर भेजें", "💬 એરર મોકલો"),
        "crash_go" to arrayOf("Continue ➜", "आगे बढ़ें ➜", "આગળ વધો ➜"),
        "lot" to arrayOf("Lot", "लॉट", "લોટ"),
        "new_lot" to arrayOf("+ Lot hisab", "+ लॉट हिसाब", "+ લોટ હિસાબ"),
        "lot_veh" to arrayOf("Vehicles in the lot", "लॉट की गाड़ियाँ", "લોટની ગાડીઓ"),
        "add_veh" to arrayOf("+ Add vehicle", "+ गाड़ी जोड़ें", "+ ગાડી ઉમેરો"),
        "veh_price" to arrayOf("Price (optional)", "कीमत (ज़रूरी नहीं)", "કિંમત (જરૂરી નથી)"),
        "lot_price" to arrayOf("Lot total price", "लॉट की कुल कीमत", "લોટની કુલ કિંમત"),
        "lot_price_h" to arrayOf("empty = vehicles total", "खाली = गाड़ियों का टोटल", "ખાલી = ગાડીઓનો ટોટલ"),
        "lot_sale" to arrayOf("Whole lot / vehicle sold", "पूरा लॉट / गाड़ी बेची", "આખો લોટ / ગાડી વેચી"),
        "lot_sale_h" to arrayOf("If the whole lot or a whole vehicle was sold, write the amount (parts go below in 3.)", "पूरा लॉट या पूरी गाड़ी बेची हो तो रकम लिखें (माल ऊपर 3. में)", "આખો લોટ કે આખી ગાડી વેચી હોય તો રકમ લખો (માલ ઉપર 3. માં)"),
        "mode_auction" to arrayOf("Sold in auction", "हराजी में बेची", "હરાજીમાં વેચી"),
        "mode_co" to arrayOf("Whole vehicle to company", "पूरी गाड़ी कंपनी को", "આખી ગાડી કંપનીને"),
        "co_give" to arrayOf("Price given by company", "कंपनी ने दी कीमत", "કંપનીએ આપેલી કિંમત"),
        "co_give_h" to arrayOf("Mudi malik gave the whole vehicle to the company at this price", "मुडी मालिक ने पूरी गाड़ी इस कीमत में कंपनी को दी", "મૂડી માલિકે આખી ગાડી આ કિંમતે કંપનીને આપી"),
        "co_maal" to arrayOf("Parts sold by company", "कंपनी ने बेचा माल", "કંપનીએ વેચેલો માલ"),
        "co_sales" to arrayOf("Company sales", "कंपनी की बिक्री", "કંપનીનું વેચાણ"),
        "co_result" to arrayOf("Company hisab", "कंपनी का हिसाब", "કંપનીનો હિસાબ"),
        "owner_res" to arrayOf("Vehicle hisab (mudi malik + khedut)", "गाड़ी का हिसाब (मुडी मालिक + खेडूत)", "ગાડીનો હિસાબ (મૂડી માલિક + ખેડૂત)"),
        "co_part" to arrayOf("Share in company", "कंपनी में हिस्सा", "કંપનીમાં ભાગ"),
        "add_co" to arrayOf("Add to my hisab", "मेरे हिसाब में जोड़ें", "મારા હિસાબમાં ઉમેરો"),
        "added_co" to arrayOf("Added", "जोड़ा", "ઉમેર્યું"),
        "co_total" to arrayOf("Total with company", "कंपनी के साथ कुल", "કંપની સાથે કુલ"),
        "final_s" to arrayOf("Final", "फ़ाइनल", "ફાઇનલ"),
        "final_btn" to arrayOf("✅ Make Final", "✅ फ़ाइनल करें", "✅ ફાઇનલ કરો"),
        "final_q" to arrayOf("After Final, nothing can be changed without the admin PIN. Haraji: only within 48 hours. After a credit time is over, never.", "फ़ाइनल के बाद एडमिन PIN के बिना कुछ नहीं बदलेगा। हराजी: सिर्फ 48 घंटे तक। उधार की मुद्दत पूरी होने के बाद कभी नहीं।", "ફાઇનલ પછી એડમિન PIN વગર કંઈ નહીં બદલાય. હરાજી: ફક્ત 48 કલાક સુધી. ઉધારની મુદત પૂરી થયા પછી ક્યારેય નહીં."),
        "lock_info" to arrayOf("Locked. Only admin can open it for a change.", "लॉक है। बदलाव के लिए सिर्फ एडमिन खोल सकते हैं।", "લોક છે. ફેરફાર માટે ફક્ત એડમિન ખોલી શકે."),
        "lock_48" to arrayOf("Change possible until", "बदलाव हो सकता है तब तक", "ફેરફાર થઈ શકે ત્યાં સુધી"),
        "lock_forever" to arrayOf("Locked for ever (credit time over / 48 hours over). Even admin cannot change it.", "हमेशा के लिए लॉक (मुद्दत पूरी / 48 घंटे पूरे)। एडमिन भी नहीं बदल सकते।", "કાયમ માટે લોક (મુદત પૂરી / 48 કલાક પૂરા). એડમિન પણ બદલી ન શકે."),
        "lock_open" to arrayOf("Change (admin PIN)", "बदलें (एडमिन PIN)", "સુધારો (એડમિન PIN)"),
        "lock_again" to arrayOf("Done – lock again", "हो गया – फिर लॉक करें", "થઈ ગયું – ફરી લોક કરો"),
        "locked_del" to arrayOf("Final hisab cannot be deleted", "फ़ाइनल हिसाब डिलीट नहीं होगा", "ફાઇનલ હિસાબ ડિલીટ નહીં થાય"),
        "adm_pin" to arrayOf("Admin PIN", "एडमिन PIN", "એડમિન PIN"),
        "adm_pin_h" to arrayOf("Needed to change a Final hisab. Keep it secret.", "फ़ाइनल हिसाब बदलने के लिए ज़रूरी। किसी को न बताएँ।", "ફાઇનલ હિસાબ બદલવા જરૂરી. કોઈને ન કહો."),
        "adm_pin_new" to arrayOf("Set admin PIN", "एडमिन PIN बनाएँ", "એડમિન PIN બનાવો"),
        "adm_pin_change" to arrayOf("Change admin PIN", "एडमिन PIN बदलें", "એડમિન PIN બદલો"),
        "book_title" to arrayOf("own account book", "अपनी खाता बुक", "પોતાની ખાતા બુક"),
        "role_co" to arrayOf("Company partner", "कंपनी भागीदार", "કંપની ભાગીદાર"),
        "book_gaadi" to arrayOf("From vehicle hisab (mudi / khedut)", "गाड़ी हिसाब से (मुडी / खेडूत)", "ગાડી હિસાબથી (મૂડી / ખેડૂત)"),
        "book_co" to arrayOf("From company", "कंपनी से", "કંપનીથી"),
        "book_total" to arrayOf("Total", "कुल", "કુલ"),
        "lot_name" to arrayOf("Lot name (e.g. GSRTC lot)", "लॉट का नाम (जैसे GSRTC लॉट)", "લોટનું નામ (જેમ કે GSRTC લોટ)"),
        "add_veh1" to arrayOf("Vehicle", "गाड़ी", "ગાડી"),
        "add_item" to arrayOf("Other item", "दूसरी चीज़", "બીજી વસ્તુ"),
        "item_name" to arrayOf("Item name (scrap, tyre …)", "चीज़ का नाम (भंगार, टायर …)", "વસ્તુનું નામ (ભંગાર, ટાયર …)"),
        "this_lot_price" to arrayOf("This lot's price", "इस लॉट की कीमत", "આ લોટની કિંમત"),
        "add_lot" to arrayOf("+ Add another lot", "+ दूसरा लॉट जोड़ें", "+ બીજો લોટ ઉમેરો"),
        "due_veh" to arrayOf("Vehicle purchase", "गाड़ी खरीदी", "ગાડી ખરીદી"),
        "due_sale" to arrayOf("Auction / company sale", "हराजी / कंपनी बिक्री", "હરાજી / કંપની વેચાણ"),
        "muddat_h" to arrayOf("⏳ Credit time (from the haraji day)", "⏳ उधार की मुद्दत (हराजी के दिन से)", "⏳ ઉધારની મુદત (હરાજીના દિવસથી)"),
        "muddat_hint" to arrayOf("Applies to every credit item that has no own time", "जिस माल की अपनी मुद्दत नहीं, उस पर यही लगेगी", "જે માલની પોતાની મુદત નથી, તેના પર આ જ લાગશે"),
        "muddat_s" to arrayOf("Credit time", "उधार मुद्दत", "ઉધાર મુદત"),
        "din" to arrayOf("Days", "दिन", "દિવસ"),
        "mahina" to arrayOf("Months", "महीने", "મહિના"),
        "pay_to" to arrayOf("Pay to (name)", "किसको देना (नाम)", "કોને આપવાના (નામ)"),
        "get_from" to arrayOf("Get from (name)", "किससे लेना (नाम)", "કોની પાસેથી લેવાના (નામ)"),
        "rokad_s" to arrayOf("Cash", "रोकड़", "રોકડ"),
        "muddat_own" to arrayOf("Days (empty = haraji time)", "दिन (खाली = हराजी मुद्दत)", "દિવસ (ખાલી = હરાજી મુદત)"),
        "comm_who" to arrayOf("Who pays the office commission?", "ऑफिस कमीशन कौन भरेगा?", "ઓફિસ કમિશન કોણ ભરશે?"),
        "comm_co" to arrayOf("Company (in its purchase)", "कंपनी (अपनी खरीदी में)", "કંપની (પોતાની ખરીદીમાં)"),
        "comm_co_h" to arrayOf("Company adds the commission to its purchase cost, then starts the haraji.", "कंपनी कमीशन अपनी खरीदी में जोड़ कर हराजी शुरू करती है।", "કંપની કમિશન પોતાની ખરીદીમાં જોડીને હરાજી શરૂ કરે છે."),
        "comm_mudi_h" to arrayOf("Commission is the mudi malik's expense (cut from the vehicle hisab).", "कमीशन मुडी मालिक का खर्च (गाड़ी के हिसाब से कटेगा)।", "કમિશન મૂડી માલિકનો ખર્ચ (ગાડીના હિસાબમાંથી કપાશે)."),
        "contacts" to arrayOf("Phone contacts", "फ़ोन कॉन्टैक्ट", "ફોન કોન્ટેક્ટ"),
        "pick_buyer" to arrayOf("Choose buyer", "खरीदार चुनें", "ખરીદનાર પસંદ કરો"),
        "party_t" to arrayOf("Buy-Sell khata book", "खरीद-बिक्री खाता बुक", "ખરીદ-વેચાણની ખાતા બુક"),
        "party_n" to arrayOf("Parties", "पार्टी", "પાર્ટી"),
        "party_stmt" to arrayOf("Pending statement", "बाकी का हिसाब", "બાકીનો હિસાબ"),
        "party_send" to arrayOf("Send pending", "बाकी भेजें", "બાકી મોકલો"),
        "items_s" to arrayOf("items", "चीज़ें", "વસ્તુ"),
        "this_month" to arrayOf("This month", "इस महीने", "આ મહિને"),
        "mob_need" to arrayOf("Mobile number is required", "मोबाइल नंबर ज़रूरी है", "મોબાઇલ નંબર ફરજિયાત છે"),
        "rem_t" to arrayOf("Collection reminders", "वसूली याद", "વસૂલી યાદ"),
        "rem_h" to arrayOf("From 3 days before the credit time, every day until paid.", "मुद्दत के 3 दिन पहले से, रोज़, जब तक चुकता न हो।", "મુદતના 3 દિવસ પહેલાથી, રોજ, ચૂકતે ન થાય ત્યાં સુધી."),
        "rem_banner" to arrayOf("to remind today (vasuli)", "को आज याद दिलाना (वसूली)", "ને આજે યાદ આપવાની (વસૂલી)"),
        "rem_tap" to arrayOf("Tap to send WhatsApp / SMS", "WhatsApp / SMS भेजने के लिए दबाएँ", "WhatsApp / SMS મોકલવા દબાવો"),
        "rem_sms_all" to arrayOf("Send SMS to everyone now", "सभी को अभी SMS भेजें", "બધાને હમણાં SMS મોકલો"),
        "rem_done" to arrayOf("Settled", "चुकता", "ચૂકતે"),
        "rem_hello" to arrayOf("Hello", "नमस्ते", "નમસ્તે"),
        "rem_share" to arrayOf("your share", "आपका हिस्सा", "તમારો ભાગ"),
        "loss_pay" to arrayOf("loss to pay", "नुकसान भरना", "નુકસાન ભરવાનું"),
        "rem_set_h" to arrayOf("Every day at 10 AM a notification comes. With auto SMS on, the phone also sends the SMS itself (normal SMS charges of your plan).", "रोज़ सुबह 10 बजे नोटिफिकेशन आएगा। ऑटो SMS चालू हो तो फ़ोन खुद SMS भेजेगा (आपके प्लान का SMS चार्ज)।", "રોજ સવારે 10 વાગે નોટિફિકેશન આવશે. ઓટો SMS ચાલુ હોય તો ફોન જાતે SMS મોકલશે (તમારા પ્લાનનો SMS ચાર્જ)."),
        "rem_auto_on" to arrayOf("Auto SMS: ON (tap to turn off)", "ऑटो SMS: चालू (बंद करने के लिए दबाएँ)", "ઓટો SMS: ચાલુ (બંધ કરવા દબાવો)"),
        "rem_auto_off" to arrayOf("Auto SMS: OFF (tap to turn on)", "ऑटो SMS: बंद (चालू करने के लिए दबाएँ)", "ઓટો SMS: બંધ (ચાલુ કરવા દબાવો)"),
        "party_tile" to arrayOf("Buy-Sell khata", "खरीद-बिक्री खाता", "ખરીદ-વેચાણ ખાતું"),
        "p_sold" to arrayOf("We sold him", "हमने उसे बेचा", "અમે તેને વેચ્યું"),
        "p_bought" to arrayOf("We bought from him", "हमने उससे खरीदा", "અમે તેની પાસેથી ખરીદ્યું"),
        "haraji_do" to arrayOf("Auction it", "हराजी करवाई", "હરાજી કરાવી"),
        "su_title" to arrayOf("Create new account", "नया खाता बनाएँ", "નવું ખાતું બનાવો"),
        "su_sub" to arrayOf("Start your own business account", "अपना बिज़नेस खाता शुरू करें", "તમારું બિઝનેસ ખાતું શરૂ કરો"),
        "u_name" to arrayOf("User name", "यूज़र का नाम", "યુઝરનું નામ"),
        "u_mobile" to arrayOf("Contact number", "कॉन्टैक्ट नंबर", "કોન્ટેક્ટ નંબર"),
        "su_send" to arrayOf("Send request via WhatsApp", "WhatsApp से रिक्वेस्ट भेजें", "WhatsApp થી રિક્વેસ્ટ મોકલો"),
        "have_acc" to arrayOf("Already have an account? Sign In", "पहले से खाता है? साइन इन", "ખાતું છે? સાઇન ઇન"),
        "no_acc" to arrayOf("New here? Create account", "नए हैं? खाता बनाएँ", "નવા છો? ખાતું બનાવો"),
        "wait_t" to arrayOf("Waiting for OTP from owner", "मालिक के OTP का इंतज़ार", "માલિકના OTP ની રાહ"),
        "wait_h" to arrayOf("Call / WhatsApp the owner if you haven't heard back", "जवाब न आए तो मालिक को फ़ोन / WhatsApp करें", "જવાબ ન આવે તો માલિકને ફોન / WhatsApp કરો"),
        "verify" to arrayOf("Verify & Continue", "वेरिफ़ाई करें और आगे बढ़ें", "વેરિફાય કરો અને આગળ વધો"),
        "resend" to arrayOf("Resend via WhatsApp", "WhatsApp से फिर भेजें", "WhatsApp થી ફરી મોકલો"),
        "call_owner" to arrayOf("Call owner", "मालिक को फ़ोन करें", "માલિકને ફોન કરો"),
        "change_acc" to arrayOf("Change name / number", "नाम / नंबर बदलें", "નામ / નંબર બદલો"),
        "si_title" to arrayOf("Sign In", "साइन इन", "સાઇન ઇન"),
        "si_bad" to arrayOf("This number is not approved on this phone – send a request", "यह नंबर इस फ़ोन पर मंज़ूर नहीं – रिक्वेस्ट भेजें", "આ નંબર આ ફોન પર મંજૂર નથી – રિક્વેસ્ટ મોકલો"),
        "blocked" to arrayOf("Blocked by owner. Ask for a new OTP. Your hisab is safe.", "मालिक ने ब्लॉक किया। नया OTP माँगें। आपका हिसाब सुरक्षित है।", "માલિકે બ્લોક કર્યું. નવો OTP માંગો. તમારો હિસાબ સલામત છે."),
        "gen_otp" to arrayOf("Generate OTP", "OTP बनाएँ", "OTP બનાવો"),
        "adm_users" to arrayOf("All users", "सभी यूज़र", "બધા યુઝર"),
        "f_ok" to arrayOf("Active", "चालू", "ચાલુ"),
        "f_no" to arrayOf("Cancelled", "रद्द", "રદ"),
        "f_block" to arrayOf("Blocked", "ब्लॉक", "બ્લોક"),
        "block_btn" to arrayOf("Block", "ब्लॉक", "બ્લોક"),
        "block_q" to arrayOf("Block this user? His app stops until you give a new OTP. His hisab stays safe.", "इस यूज़र को ब्लॉक करें? नया OTP देने तक उसकी ऐप बंद रहेगी। उसका हिसाब सुरक्षित रहेगा।", "આ યુઝરને બ્લોક કરવો? નવો OTP આપો ત્યાં સુધી તેની એપ બંધ રહેશે. તેનો હિસાબ સલામત રહેશે."),
        "u_total" to arrayOf("Users", "यूज़र", "યુઝર"),
        "u_week" to arrayOf("active 7 days", "7 दिन में चालू", "7 દિવસમાં ચાલુ"),
        "u_today" to arrayOf("today", "आज", "આજે"),
        "u_yday" to arrayOf("yesterday", "कल", "ગઈકાલે"),
        "u_days_ago" to arrayOf("days ago", "दिन पहले", "દિવસ પહેલા"),
        "u_last" to arrayOf("Last used", "आखिरी बार", "છેલ્લે વાપરી"),
        "u_hisab" to arrayOf("Hisab", "हिसाब", "હિસાબ"),
        "u_lasth" to arrayOf("last hisab", "आखिरी हिसाब", "છેલ્લો હિસાબ"),
        "u_nodata" to arrayOf("No usage info yet (app not opened with internet)", "अभी जानकारी नहीं (इंटरनेट के साथ ऐप नहीं खुली)", "હજી માહિતી નથી (ઇન્ટરનેટ સાથે એપ ખૂલી નથી)"),
        "u_share" to arrayOf("Share user list", "यूज़र लिस्ट भेजें", "યુઝર યાદી મોકલો"),
        "made" to arrayOf("Made with Kabadi Market Hisab", "कबाड़ी मार्केट हिसाब से बना", "કબાડી માર્કેટ હિસાબથી બનાવ્યું")
    )

    fun t(k: String): String = T[k]?.get(lang) ?: k

    /** name of a credit line (vehicle price / auction sale have no typed name) */
    fun ln(l: Line): String = when (l.key) { "veh" -> "🚚 " + t("due_veh"); "sale" -> "🔨 " + t("due_sale"); else -> l.name }
}
