import { Platform } from "react-native";
import * as FileSystem from "expo-file-system/legacy";
import * as Sharing from "expo-sharing";

import { api } from "@/src/api/client";

const XLSX_MIME = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";

// Same web-download shim as backup.tsx's exportExcel (that screen already
// downloads a server-generated .xlsx this exact way) — reused here so every
// "Export to Excel" button in the app goes through one code path instead of
// each screen reimplementing it.
function webDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 2000);
}

// Fetches an .xlsx generated by the backend (openpyxl — no spreadsheet
// library needed on the client at all) at `path` and hands it to the user:
// a browser download on web, or the native share sheet (same
// FileSystem.downloadAsync + Sharing.shareAsync pattern already proven by
// backup.tsx's Excel export) so it can be saved to Drive, emailed, etc.
export async function exportExcel(path: string, filename: string): Promise<void> {
  const token = await api.getToken();
  const url = `${api.base}${path}`;
  if (Platform.OS === "web") {
    const res = await fetch(url, { headers: { Authorization: `Bearer ${token}` } });
    if (!res.ok) throw new Error(`Export failed (${res.status})`);
    const blob = await res.blob();
    webDownload(blob, filename);
  } else {
    const uri = FileSystem.documentDirectory + filename;
    const dl = await FileSystem.downloadAsync(url, uri, { headers: { Authorization: `Bearer ${token}` } });
    if (dl.status && dl.status >= 400) throw new Error(`Export failed (${dl.status})`);
    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(dl.uri, { mimeType: XLSX_MIME, dialogTitle: filename });
    }
  }
}
