plugins {
    id 'com.android.application'
}
android {
    namespace 'com.merahisab.app'
    compileSdk 34
    defaultConfig {
        applicationId 'com.merahisab.app'
        minSdk 29
        targetSdk 34
        versionCode Integer.parseInt(System.getenv('GITHUB_RUN_NUMBER') ?: '1')
        versionName '1.0.' + (System.getenv('GITHUB_RUN_NUMBER') ?: '0')
    }
    signingConfigs {
        release {
            storeFile file('mera.jks')
            storePassword 'nirmaan123'
            keyAlias 'nirmaan'
            keyPassword 'nirmaan123'
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
